import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className=' lg:max-w-[900px] flex flex-col min-h-screen lg:px-16 py-8  mx-auto  shadow-xl  '>

        
        <Navbar/>

          <div  className='flex-auto' >
            {children}  {/*children = everything in app->page.tsx */}
          </div>
        

        <Footer/>

      </div>

        </body>
    </html>
  )
}
